version: 2
jobs:
  build:
    working_directory: ~/my_sensors
    docker:
      - image: elixir:1.5.2
        environment:
          MIX_ENV: test
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar
      - run: mix deps.get
      - run: mix coveralls.circle
